### PR TITLE
Compressed site images for reduction of 15-50%.

### PR DESCRIPTION
**Pull request by TzZek**

### CODE REVIEW

**Comment by sunnyflunk** [comment]
Nice! Could this be added to https://github.com/serpent-linux/website/blob/main/screenieopt.sh to use for future images?

**Comment by TzZek** [comment]
> Nice! Could this be added to https://github.com/serpent-linux/website/blob/main/screenieopt.sh to use for future images?

[TinyPNG](https://tinypng.com/): Limit is 500 compressions per month. (Though should be plenty)
I'm unsure I use https://github.com/websperts/tinypng-cli
Alternatively: https://marketplace.visualstudio.com/items?itemName=andi1984.tinypng

I've just found it works out better than optipng, but I haven't tinkered with any deeper level optipng.

A quick google search though came up w/ these as possible options however I haven't personally tested it.
`
optipng -o7 -strip all <image.png>
`

**Comment by ikeycode** [comment]
Oh you beauty.

**Comment by sunnyflunk** [comment]
Just for reference, while I'm a fan of (and use) tinypng, it isn't a lossless change (reduces # of colours and adjusts them in the image to a close match) so outputs should always be reviewed. I've seen it mess up an image quite badly.

**Comment by TzZek** [comment]
@sunnyflunk , oh I've never had that issue personally but thank you for the insight, I appreciate it.

**Comment by sunnyflunk** [comment]
From memory it was part of the image which blended similar colours together. So it ended up looking pixelated. As an example, when zoomed in looks a bit janky in parts. This isn't too bad but have seen it worse than this.

Screenshot_20200914_091105

**Pull request merged**
